1. CSV 파일 로컬에서 불러오기

In [1]:
import pandas as pd

# 로컬 CSV 파일 읽기
file_path = "C:/Users/Admin/Desktop/3-1/인공지능개론/week2/iris.csv" 
df = pd.read_csv(file_path)

df.head(), df.columns

print(df)

     SepalLength  SepalWidth  PetalLength  PetalWidth            Name
0            5.1         3.5          1.4         0.2     Iris-setosa
1            4.9         3.0          1.4         0.2     Iris-setosa
2            4.7         3.2          1.3         0.2     Iris-setosa
3            4.6         3.1          1.5         0.2     Iris-setosa
4            5.0         3.6          1.4         0.2     Iris-setosa
..           ...         ...          ...         ...             ...
145          6.7         3.0          5.2         2.3  Iris-virginica
146          6.3         2.5          5.0         1.9  Iris-virginica
147          6.5         3.0          5.2         2.0  Iris-virginica
148          6.2         3.4          5.4         2.3  Iris-virginica
149          5.9         3.0          5.1         1.8  Iris-virginica

[150 rows x 5 columns]


2. CSV파일 온라인에서 불러오기

In [3]:
import pandas as pd

url = "https://raw.githubusercontent.com/MyungKyuYi/AI-class/main/mobile.csv"

df = pd.read_csv(url)

df.head(), df.columns

print(df)

      battery_power  blue  clock_speed  dual_sim  fc  four_g  int_memory  \
0               842     0          2.2         0   1       0           7   
1              1021     1          0.5         1   0       1          53   
2               563     1          0.5         1   2       1          41   
3               615     1          2.5         0   0       0          10   
4              1821     1          1.2         0  13       1          44   
...             ...   ...          ...       ...  ..     ...         ...   
1995            794     1          0.5         1   0       1           2   
1996           1965     1          2.6         1   0       0          39   
1997           1911     0          0.9         1   1       1          36   
1998           1512     0          0.9         0   4       1          46   
1999            510     1          2.0         1   5       1          45   

      m_dep  mobile_wt  n_cores  ...  px_height  px_width   ram  sc_h  sc_w  \
0       

3. 엑셀 파일 로컬에서 불러오기

In [5]:
import pandas as pd

# 엑셀 파일 변환
df = pd.read_excel('C:/Users/Admin/Desktop/3-1/인공지능개론/week2/combined_dataset-1.xlsx')

print("엑셀 파일:")
print(df)

df.to_csv('combined.csv', index=False) 
df_csv = pd.read_csv('combined.csv')

print("\nCSV로 변환:")

print(df_csv)


엑셀 파일:
     Num.  subject_ID Sex(M/F)  Age(year)  Height(cm)  Weight(kg)  \
0       1           2   Female         45         152          63   
1       1           2   Female         45         152          63   
2       1           2   Female         45         152          63   
3       2           3   Female         50         157          50   
4       2           3   Female         50         157          50   
..    ...         ...      ...        ...         ...         ...   
652   218         418     Male         25         173          63   
653   218         418     Male         25         173          63   
654   219         419     Male         24         175          58   
655   219         419     Male         24         175          58   
656   219         419     Male         24         175          58   

     Systolic Blood Pressure(mmHg)  Diastolic Blood Pressure(mmHg)  \
0                              161                              89   
1                       

C:\Users\Admin\AppData\Local\Temp\ipykernel_17756\1044950458.py:10: DtypeWarning: Columns (12,13) have mixed types. Specify dtype option on import or set low_memory=False.
  df_csv = pd.read_csv('combined.csv')


4. 엑셀 파일 온라인에서 불러오기

In [7]:
import pandas as pd

# 엑셀 파일 변환
url = 'https://raw.githubusercontent.com/MyungKyuYi/AI-class/main/combined_dataset-1.xlsx'

df = pd.read_excel(url)

print("\nbDataFrame:")

print(df)


bDataFrame:
     Num.  subject_ID Sex(M/F)  Age(year)  Height(cm)  Weight(kg)  \
0       1           2   Female         45         152          63   
1       1           2   Female         45         152          63   
2       1           2   Female         45         152          63   
3       2           3   Female         50         157          50   
4       2           3   Female         50         157          50   
..    ...         ...      ...        ...         ...         ...   
652   218         418     Male         25         173          63   
653   218         418     Male         25         173          63   
654   219         419     Male         24         175          58   
655   219         419     Male         24         175          58   
656   219         419     Male         24         175          58   

     Systolic Blood Pressure(mmHg)  Diastolic Blood Pressure(mmHg)  \
0                              161                              89   
1                 

5. Diabates 자료를 통해 KNN 알고리즘 적용

In [9]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsRegressor
from sklearn.metrics import mean_squared_error

url = "https://raw.githubusercontent.com/MyungKyuYi/AI-class/refs/heads/main/diabetes.csv"

df = pd.read_csv(url)

df.head(), df.columns

print(df)

X = df.drop('Outcome', axis=1)
y = df["Outcome"]

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# KNN 알고리즘 적용
model = KNeighborsRegressor()
model_name = "KNN"
    
# 훈련
model.fit(X_train, y_train)

# 훈련된 데이터를 가지고 test 데이터를 predict
y_pred = model.predict(X_test)

# 정답과 test 결과값(y_pred) 비교
mse = mean_squared_error(y_test, y_pred)

print(f"{model_name} 모델의 평균 제곱 오차: {mse:.2f}")

     Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0              6      148             72             35        0  33.6   
1              1       85             66             29        0  26.6   
2              8      183             64              0        0  23.3   
3              1       89             66             23       94  28.1   
4              0      137             40             35      168  43.1   
..           ...      ...            ...            ...      ...   ...   
763           10      101             76             48      180  32.9   
764            2      122             70             27        0  36.8   
765            5      121             72             23      112  26.2   
766            1      126             60              0        0  30.1   
767            1       93             70             31        0  30.4   

     DiabetesPedigreeFunction  Age  Outcome  
0                       0.627   50        1  
1                  

6. Diabates 자료를 통해 KNN 알고리즘 적용 및 실제값과 예측값 비교

In [11]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsRegressor
from sklearn.metrics import mean_squared_error

url = "https://raw.githubusercontent.com/MyungKyuYi/AI-class/refs/heads/main/diabetes.csv"

df = pd.read_csv(url)

df.head(), df.columns

print(df)

X = df.drop('Outcome', axis=1)
y = df["Outcome"]

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

model = KNeighborsRegressor()
model_name = "KNN"
    
# 훈련
model.fit(X_train, y_train)

# 훈련된 데이터를 가지고 test 데이터를 predict
y_pred = model.predict(X_test)

# 정답과 test 결과값(y_pred) 비교
mse = mean_squared_error(y_test, y_pred)

print(f"{model_name} 모델의 평균 제곱 오차: {mse:.2f}")

print("실제 값  | 예측 값")
print("-" * 50)
for actual, predicted in zip(y_test[10:20], y_pred[10:20]): 
    print(f"{actual:^7} | {predicted:^7.2f}")

     Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0              6      148             72             35        0  33.6   
1              1       85             66             29        0  26.6   
2              8      183             64              0        0  23.3   
3              1       89             66             23       94  28.1   
4              0      137             40             35      168  43.1   
..           ...      ...            ...            ...      ...   ...   
763           10      101             76             48      180  32.9   
764            2      122             70             27        0  36.8   
765            5      121             72             23      112  26.2   
766            1      126             60              0        0  30.1   
767            1       93             70             31        0  30.4   

     DiabetesPedigreeFunction  Age  Outcome  
0                       0.627   50        1  
1                  

7. 2주차 실습과제 (titanic 자료 실습)

In [21]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.svm import SVR
from sklearn.ensemble import RandomForestRegressor
from sklearn.tree import DecisionTreeRegressor
from sklearn.metrics import mean_squared_error
from sklearn.neighbors import KNeighborsRegressor 
from sklearn.preprocessing import LabelEncoder
from sklearn.metrics import accuracy_score, confusion_matrix

# LabelEncoder 객체 생성
encoder = LabelEncoder()

# 1. 데이터 로딩
file_path = "https://raw.githubusercontent.com/MyungKyuYi/AI-class/refs/heads/main/titanic.csv"
df = pd.read_csv(file_path)

# 2. 결측치 확인
print(df.isnull().sum())
print("================================================================")

# 3. 결측치 제거 (Age의 결측치는 평균나이로)
df['Age'].fillna(df['Age'].mean(), inplace=True)
df.dropna(inplace=True)
print(df)
print("================================================================")

# 4. 불균형 여부 확인 (생존자 확인)
print(df['Survived'].value_counts())
print(df['Survived'].value_counts(normalize=True))  # 비율
print("================================================================")

# 5. 불필요한 컬럼 제거
df.drop(["Name", "Ticket", "Embarked"], axis=1, inplace=True)
print(df)
print("================================================================")

# 6. 인코딩(머신러닝과 딥러닝의 모든 값을 숫자로 변경, 단 머신러닝의 label은 제외)
for column in df.select_dtypes(include=['object']).columns:
    df[column] = encoder.fit_transform(df[column])
print(df)
print("================================================================")

# 특징과 결과값 지정
X = df.drop('Survived', axis=1)
Y = df["Survived"]

# 훈련 데이터와 테스트 데이터 분리 (80% 훈련, 20% 테스트)
X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size=0.2, random_state=42)

# 모델 정의
models = {
    'Linear Regression': LinearRegression(),
    'Support Vector Machine': SVR(),
    'Random Forest': RandomForestRegressor(),
    'Decision Tree': DecisionTreeRegressor(),
    'K-Nearest Neighbors': KNeighborsRegressor()
}

for model_name, model in models.items():
    model.fit(X_train, y_train)  # 훈련
    y_pred = model.predict(X_test)  # 예측
    
    # 연속적인 예측값을 0 또는 1로 변환해야 정확도와 혼동 행렬 확인 가능
    y_pred_binary = np.where(y_pred > 0.5, 1, 0)


    print(f"{model_name} 모델")
    print("정확도(Accuracy):", accuracy_score(y_test, y_pred_binary))
    print("혼동 행렬(Confusion Matrix):\n", confusion_matrix(y_test, y_pred_binary))
    print("================================================================")

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64
     PassengerId  Survived  Pclass  \
1              2         1       1   
3              4         1       1   
6              7         0       1   
10            11         1       3   
11            12         1       1   
..           ...       ...     ...   
871          872         1       1   
872          873         0       1   
879          880         1       1   
887          888         1       1   
889          890         1       1   

                                                  Name     Sex   Age  SibSp  \
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
6                              McCarthy, Mr. Timothy J    male  5

C:\Users\Admin\AppData\Local\Temp\ipykernel_17756\1312820429.py:25: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Age'].fillna(df['Age'].mean(), inplace=True)


Random Forest 모델
정확도(Accuracy): 0.8048780487804879
혼동 행렬(Confusion Matrix):
 [[ 5  3]
 [ 5 28]]
Decision Tree 모델
정확도(Accuracy): 0.7317073170731707
혼동 행렬(Confusion Matrix):
 [[ 3  5]
 [ 6 27]]
K-Nearest Neighbors 모델
정확도(Accuracy): 0.6829268292682927
혼동 행렬(Confusion Matrix):
 [[ 3  5]
 [ 8 25]]
