결측치 확인, 결측치 제거 ..

In [17]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.svm import SVR
from sklearn.ensemble import RandomForestRegressor
from sklearn.tree import DecisionTreeRegressor
from sklearn.metrics import mean_squared_error
from sklearn.neighbors import KNeighborsRegressor 
from sklearn.preprocessing import LabelEncoder
from sklearn.metrics import accuracy_score, confusion_matrix
import seaborn as sns
car = pd.read_csv("C:/Users/Admin/Desktop/3-1/인공지능개론/week3/car_evaluation.csv")

car.head()


vhigh vhigh.1  2 2.1  small   low  unacc
0  vhigh   vhigh  2   2  small   med  unacc
1  vhigh   vhigh  2   2  small  high  unacc
2  vhigh   vhigh  2   2    med   low  unacc
3  vhigh   vhigh  2   2    med   med  unacc
4  vhigh   vhigh  2   2    med  high  unacc

In [18]:
car.head(), car.columns

print(car)

      vhigh vhigh.1      2   2.1  small   low  unacc
0     vhigh   vhigh      2     2  small   med  unacc
1     vhigh   vhigh      2     2  small  high  unacc
2     vhigh   vhigh      2     2    med   low  unacc
3     vhigh   vhigh      2     2    med   med  unacc
4     vhigh   vhigh      2     2    med  high  unacc
...     ...     ...    ...   ...    ...   ...    ...
1722    low     low  5more  more    med   med   good
1723    low     low  5more  more    med  high  vgood
1724    low     low  5more  more    big   low  unacc
1725    low     low  5more  more    big   med   good
1726    low     low  5more  more    big  high  vgood

[1727 rows x 7 columns]


In [22]:
print(car.isnull().sum()) # 결측치 없음

vhigh      0
vhigh.1    0
2          0
2.1        0
small      0
low        0
unacc      0
dtype: int64


In [28]:
# 인코딩
encoder = LabelEncoder()

for column in car.select_dtypes(include=['object']).columns:
    car[column] = encoder.fit_transform(car[column])
print(car)

      vhigh  vhigh.1  2  2.1  small  low  unacc
0         3        3  0    0      2    2      2
1         3        3  0    0      2    0      2
2         3        3  0    0      1    1      2
3         3        3  0    0      1    2      2
4         3        3  0    0      1    0      2
...     ...      ... ..  ...    ...  ...    ...
1722      1        1  3    2      1    2      1
1723      1        1  3    2      1    0      3
1724      1        1  3    2      0    1      2
1725      1        1  3    2      0    2      1
1726      1        1  3    2      0    0      3

[1727 rows x 7 columns]


In [44]:
# 특징과 결과값 지정
X = car.drop(['unacc'], axis=1)
Y = car['unacc']

print(X)
print(Y)

# 훈련 데이터와 테스트 데이터 분리 (80% 훈련, 20% 테스트)
X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size=0.2, random_state=42)

      vhigh  vhigh.1  2  2.1  small  low
0         3        3  0    0      2    2
1         3        3  0    0      2    0
2         3        3  0    0      1    1
3         3        3  0    0      1    2
4         3        3  0    0      1    0
...     ...      ... ..  ...    ...  ...
1722      1        1  3    2      1    2
1723      1        1  3    2      1    0
1724      1        1  3    2      0    1
1725      1        1  3    2      0    2
1726      1        1  3    2      0    0

[1727 rows x 6 columns]
0       2
1       2
2       2
3       2
4       2
       ..
1722    1
1723    3
1724    2
1725    1
1726    3
Name: unacc, Length: 1727, dtype: int32


In [48]:
# 전처리
from sklearn.preprocessing import StandardScaler
ss = StandardScaler()
ss.fit(X_train) # StandardScaler 꼭 train 데이터의 input으로 해줘야한다.
train_scaled = ss.transform(X_train)
test_scaled = ss.transform(X_test)

In [64]:
# 모델 정의
models = {
    'Decision Tree': DecisionTreeRegressor(),
    'K-Nearest Neighbors': KNeighborsRegressor()
}

print("Linear Regression")
lr = LinearRegression()
lr.fit(X_train, y_train)
print(lr.predict(X_test[:5]))
print("정확도(Accuracy):", accuracy_score(y_test, y_pred_binary))
print("혼동 행렬(Confusion Matrix):\n", confusion_matrix(y_test, y_pred_binary))

print("rf")
svm = RandomForestRegressor()
lr.fit(X_train, y_train)
print(lr.predict(X_test[:5]))
print("정확도(Accuracy):", accuracy_score(y_test, y_pred_binary))
print("혼동 행렬(Confusion Matrix):\n", confusion_matrix(y_test, y_pred_binary))

print("svr")
svm = SVR()
lr.fit(X_train, y_train)
print(lr.predict(X_test[:5]))
print("정확도(Accuracy):", accuracy_score(y_test, y_pred_binary))
print("혼동 행렬(Confusion Matrix):\n", confusion_matrix(y_test, y_pred_binary))

for model_name, model in models.items():
    model.fit(X_train, y_train)  # 훈련
    y_pred = model.predict(X_test)  # 예측
    
    # 연속적인 예측값을 0 또는 1로 변환해야 정확도와 혼동 행렬 확인 가능
    y_pred_binary = np.where(y_pred > 0.5, 1, 0)


    print(f"{model_name} 모델")
    print("정확도(Accuracy):", accuracy_score(y_test, y_pred_binary))
    print("혼동 행렬(Confusion Matrix):\n", confusion_matrix(y_test, y_pred_binary))

Linear Regression
[1.71474164 1.58537081 1.69427692 1.42515971 1.21997992]
정확도(Accuracy): 0.08092485549132948
혼동 행렬(Confusion Matrix):
 [[ 13  64   0   0]
 [  0  15   0   0]
 [  0 237   0   0]
 [  0  17   0   0]]
rf
[1.71474164 1.58537081 1.69427692 1.42515971 1.21997992]
정확도(Accuracy): 0.08092485549132948
혼동 행렬(Confusion Matrix):
 [[ 13  64   0   0]
 [  0  15   0   0]
 [  0 237   0   0]
 [  0  17   0   0]]
svr
[1.71474164 1.58537081 1.69427692 1.42515971 1.21997992]
정확도(Accuracy): 0.08092485549132948
혼동 행렬(Confusion Matrix):
 [[ 13  64   0   0]
 [  0  15   0   0]
 [  0 237   0   0]
 [  0  17   0   0]]
Decision Tree 모델
정확도(Accuracy): 0.2514450867052023
혼동 행렬(Confusion Matrix):
 [[ 74   3   0   0]
 [  2  13   0   0]
 [  1 236   0   0]
 [  1  16   0   0]]
K-Nearest Neighbors 모델
정확도(Accuracy): 0.08092485549132948
혼동 행렬(Confusion Matrix):
 [[ 13  64   0   0]
 [  0  15   0   0]
 [  0 237   0   0]
 [  0  17   0   0]]
